"""initial schema

Revision ID: 60b5d17857bd
Revises: 
Create Date: 2026-08-20 12:15:14.084428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b5d17857bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('integration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('team_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('join_code', sa.String(length=12), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('dynamic', sa.JSON(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_join_code'), 'sessions', ['join_code'], unique=True)
    op.create_table('action_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('assignee', sa.String(length=200), nullable=True),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_items')
    op.drop_index(op.f('ix_sessions_join_code'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('teams')
    # ### end Alembic commands ###
