"""add created_by to sessions

Revision ID: 9cc6de103894
Revises: 60b5d17857bd
Create Date: 2026-08-21 12:42:51.392287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cc6de103894'
down_revision: Union[str, Sequence[str], None] = '60b5d17857bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_by', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'created_by')
    # ### end Alembic commands ###
